### ISSUE TITLE
Some information about Commanders gone in latest master-version?

### ISSUE THREAD

**Issue by BafDyce** [rster2002/ed-journals#94]
Hi :)

I started building a small tool on top of this crate (based on version `0.5.1`) a few weeks ago. Since I contributed some stuff last week, I wanted to rebase my tool on top of the current `master` branch of `ed-journals`.
Unfortunately, I realized that the `CommanderState` (which was renamed to `LogState`) lost some information? For example, I cannot find the commander name anymore?
Was this on purpose? Are you planning to bring this back before publishing version `0.6.0`? Or was this field moved to some other struct which I missed? I did not check yet whether other pieces of information are now also gone.

**Comment by rster2002** [comment]
Hi! Yes I've been making a lot of changes but have not documented a lot of it yet as I'm still working through adding doc comments in #81. It was intentional to remove commander data from the LogState as I wanted to be able to create the possibility to track state independent of any information about a commander. That behaviour has been moved to GameState, but it seems that the commander name has fallen through the cracks. A fix is in the works for this.

**Comment by rster2002** [comment]
A fix has been pushed to master. Let me know what you think!
